site_name: Mario's Blog

theme:
  name: material
  palette:
    primary: orange
  font:
    text: STSong

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:
  - C:
    - C/c-study.md
